version: '3.9'

services:
  postgres:
    image : postgres:16-alpine
    environment:
      - POSTGRES_USER:otellocal
      - POSTGRES_PASSWORD: otellocal
      - POSTGRES_DB:       otellocal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otellocal"]
      interval: 5s
      timeout: 5s
      retries: 5
      

volumes:
  pgdata:          